apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  type: NodePort
  selector:
    env: prod
  ports:
    - port: 80
      targetPort: 80
      # by defauld Kubernetes control plane will allocate a port from a range 30000-32767
      nodePort: 30010
