apiVersion: v1
kind: Pod
metadata:
  name: pod-from-node-selector-4
  labels:
    env: prod
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
   #name: w1  
