apiVersion: v1
kind: Pod
metadata:
  name: pod-from-node-selector-2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    #name: W1
